path: dataset
train: train/images
val: valid/images
test: test/images

nc: 7
names: ['Bistay_sand', 'Cement', 'Gravel', 'Hollow_blocks', 'Rebar', 'Sack', 'Skim_coat']

roboflow:
  workspace: cgg-marketing-hardware-supplies
  project: hardware-supplies
  version: 11
  license: CC BY 4.0
  url: https://universe.roboflow.com/cgg-marketing-hardware-supplies/hardware-supplies/dataset/11